
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

permalink: "/:path/:name"


title: dn42 wiki

keywords: dn42,wiki,routing,bgp

lang: "en"

