
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

url: "https://dn42.obl.ong"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      sitemap: true

permalink: "/:path/:name"

exclude:
  - wiki/

title: dn42 wiki

keywords: dn42,wiki,routing,bgp

lang: "en"

