name: Deplay wiki
on:
  schedule:
      - cron:  '34 */6 * * *'
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone wiki
        run: git clone https://$USERNAME:$PASSWORD@git.dn42.dev/wiki/wiki.git
        env:
          USERNAME: ${{ secrets.DN42_GIT_USERNAME }}
          PASSWORD: ${{ secrets.DN42_GIT_PASSWORD }}
      - name: Linking files
        run: cp -r wiki/* .
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install jekyll
        run: bundle install
      - name: Build static side
        run: bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
